# This workflow will post an update to the official Telegram channel.
# Triggered when a new release is created in the GitHub repository.

name: Post update to Telegram

on:
  release:
    types: [published]

jobs:
  post_to_telegram:
    name: Post update to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Telegram
        uses: telegram/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
      
      - name: Post update to Telegram
        uses: telegram/post-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          text: ${{ github.event.release.body }}
          parse_mode: Markdown
          disable_web_page_preview: true
          disable_notification: true

